@baseUrl = http://localhost:5000/api/v1
@contentType = application/json

### Register
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
  "email": "test-user@example.com",
  "username": "testuser",
  "displayName": "Test User",
  "password": "StrongPassword123!"
}

### Verify OTP
POST {{baseUrl}}/auth/verify-otp
Content-Type: {{contentType}}

{
  "identifier": "test-user@example.com",
  "otp": "295338"
}

### Login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "identifier": "test-user@example.com",
  "password": "StrongPassword123!"
}

### Refresh
POST {{baseUrl}}/auth/refresh

### My Sessions
GET {{baseUrl}}/auth/sessions

### My Profile
GET {{baseUrl}}/users/me

### Update Profile
POST {{baseUrl}}/users/profile
Content-Type: {{contentType}}

{
  "displayName": "Updated Name"
}

### 2FA Generate
POST {{baseUrl}}/auth/2fa/generate

### 2FA Turn On
POST {{baseUrl}}/auth/2fa/turn-on
Content-Type: {{contentType}}

{
  "code": "123456"
}

### Logout
POST {{baseUrl}}/auth/logout

### Revoke All
POST {{baseUrl}}/auth/sessions/revoke-all
