export const AUTH_EVENT_ACTIONS = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGIN_SUCCESS_2FA: 'LOGIN_SUCCESS_2FA',
  LOGIN_PHONE_SUCCESS: 'LOGIN_PHONE_SUCCESS',
  REGISTER_PHONE_SUCCESS: 'REGISTER_PHONE_SUCCESS',
  PASSWORD_RESET_SUCCESS: 'PASSWORD_RESET_SUCCESS',
  PASSWORD_CHANGE_SUCCESS: 'PASSWORD_CHANGE_SUCCESS',
  LOGOUT: 'LOGOUT',
  SESSION_REVOKED: 'SESSION_REVOKED',
  EMAIL_CHANGED: 'EMAIL_CHANGED',
  PHONE_CHANGED: 'PHONE_CHANGED',
  TWO_FA_ENABLED: '2FA_ENABLED',
  TWO_FA_DISABLED: '2FA_DISABLED',
} as const;

export const AUTH_EVENT_STATUS = {
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
} as const;

export type AuthEventAction =
  (typeof AUTH_EVENT_ACTIONS)[keyof typeof AUTH_EVENT_ACTIONS];
export type AuthEventStatus =
  (typeof AUTH_EVENT_STATUS)[keyof typeof AUTH_EVENT_STATUS];
